version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: document_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  redis:
    image: "redis:alpine"

